version: "3"
  
volumes:
  node_modules:
  postgres_data:

services:
  web:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - TZ=$TZ
    ports:
      - "8000:8000"
    volumes:
      - .:$PROJECT_ROOT_DIR
      - node_modules:$PROJECT_ROOT_DIR/node_modules

  postgres:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - TZ=$TZ
      - PGDATA=/var/lib/postgresql/data/pgdata
