"""Add cascade='all,delete-orpahn' to User.urls

Revision ID: 02c0764b1313
Revises: 58b794396519
Create Date: 2021-04-07 15:42:23.197053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c0764b1313'
down_revision = '58b794396519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
