"""Define ShortUrl model

Revision ID: 38ce38f7cfc7
Revises: d4867f3a4c0a
Create Date: 2021-04-06 16:04:35.357781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ce38f7cfc7'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorturl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=2048), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shorturl_destination'), 'shorturl', ['destination'], unique=False)
    op.create_index(op.f('ix_shorturl_id'), 'shorturl', ['id'], unique=False)
    op.create_index(op.f('ix_shorturl_key'), 'shorturl', ['key'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_shorturl_key'), table_name='shorturl')
    op.drop_index(op.f('ix_shorturl_id'), table_name='shorturl')
    op.drop_index(op.f('ix_shorturl_destination'), table_name='shorturl')
    op.drop_table('shorturl')
    # ### end Alembic commands ###
