"""Add check ondelete='CASCADE' to ShortUrl.owner_id FK

Revision ID: 58b794396519
Revises: d6c155422e16
Create Date: 2021-04-07 15:38:37.100772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b794396519'
down_revision = 'd6c155422e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shorturl_owner_id_fkey', 'shorturl', type_='foreignkey')
    op.create_foreign_key(None, 'shorturl', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shorturl', type_='foreignkey')
    op.create_foreign_key('shorturl_owner_id_fkey', 'shorturl', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
