"""Add check constraint to url_count

Revision ID: d6c155422e16
Revises: 80ab7fd4ca8f
Create Date: 2021-04-07 15:25:56.792640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c155422e16'
down_revision = '80ab7fd4ca8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
