"""Add created_at to ShortUrl

Revision ID: ee7fd1a2a1f3
Revises: ef99f0978944
Create Date: 2021-04-07 20:00:58.561803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7fd1a2a1f3'
down_revision = 'ef99f0978944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shorturl', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shorturl', 'created_at')
    # ### end Alembic commands ###
