"""Remove url_count

Revision ID: ef99f0978944
Revises: 02c0764b1313
Create Date: 2021-04-07 16:12:37.880508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef99f0978944'
down_revision = '02c0764b1313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('url_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
